name: S3 Bucket Antivirus Lambda

on: workflow_dispatch

env:
  REPO_BUCKET: s3://lambda-cfn-repository.rentpal

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Build Lambda function
        run: |
          make archive

      - name: Publish artifacts to S3
        shell: bash
        run: |
          bin/generate_git_version_name.sh > version.properties
          export $(cat version.properties | xargs)
          aws s3 mv ./build/lambda.zip $REPO_BUCKET/s3-bucket-av-lambda-$versionName.zip
